services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=local_dev_key
      - GENERIC_TIMEZONE=${TZ:-Europe/Paris}
      - TZ=${TZ:-Europe/Paris}
      # Configuration pour Ngrok (optionnel si pas de tunnel)
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - n8n_data_local:/home/node/.n8n

volumes:
  n8n_data_local:
